# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e51753fda6d9c84916981be471abaf0984088b7a74fca01cb5b7cac999b55db5e500fe139b5490bfff393bd35140477380074566752ea7bf1982f0de4c2608f

test:
  secret_key_base: 74b54daf8e2065b67a0b48eabd201ed8ec45075898a3a827efd0f72998141a724c008a6e873e85d6e8bc8e9661bce8eb17bc297525a254ad0baba685f88efae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
